### ISSUE TITLE
What does `dynamic: true` mean in userUpdate.ts?

### ISSUE THREAD

**Issue by Derpitron** [peterthehan/discord-audit-log-bot#11]
Hi, I'm quite new to making discord bots and have zero experience with TypeScript. What does `dynamic: true` mean in lines 12 and 13 of [userUpdate.ts](https://github.com/peterthehan/discord-audit-log-bot/blob/main/src-discord-audit-log-bot/handlers/userUpdate.ts)? 

![image](https://user-images.githubusercontent.com/46134462/146975134-c1bb4d1f-4c76-4858-9fb2-c79902cf59ce.png)

**Comment by Johannes7k75** [comment]
that the avatar can be animated like if the avatar is a gif.
If false its only a static image

**Comment by peterthehan** [comment]
That option is passed to the function so that we can fetch gif avatars from nitro users.
