### ISSUE TITLE
Where do I declare the webhook link?

### ISSUE THREAD

**Issue by Derpitron** [peterthehan/discord-audit-log-bot#12]
upon `npm start`ing the bot, I get an error: 

`Error [WEBHOOK_TOKEN_UNAVAILABLE]: This action requires a webhook token, but none is available.`

Where should I declare the webhook link?

**Comment by peterthehan** [comment]
Make sure the bot has `Manage Webhook` permissions, it will create a Webhook if one doesn't exist https://github.com/peterthehan/discord-audit-log-bot/blob/main/src-discord-audit-log-bot/util/sendWebhookMessage.ts#L14

**Comment by Derpitron** [comment]
Hello, I have given the bot administrator permissions through a role, but it still errors out.

**Comment by peterthehan** [comment]
Hmm, the bot doesn't require a webhook link because it's fetched programmatically. Feel free to join the server for quicker troubleshooting feedback. I might need more info to help you.
